server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5440/movienight}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:movienight}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:movienight}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6380}

logging.level.ru.itis.movienight=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

kinopoisk.api.url=https://kinopoiskapiunofficial.tech/api/v2.2
kinopoisk.api.key=f924dfc1-704d-4ac7-9a72-a24dca2b06dd

admin.username=admin
admin.email=admin@mail.ru
admin.password=admin1