apiVersion: apps/v1
kind: Deployment
metadata:
  name: movienight-backend
  namespace: team-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movienight-backend
  template:
    metadata:
      labels:
        app: movienight-backend
    spec:
      containers:
        - name: movienight-backend
          image: docker.io/asilya18/movienight-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef: { name: postgres-secret, key: POSTGRES_USER }
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef: { name: postgres-secret, key: POSTGRES_PASSWORD }
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
